# Generated by Django 2.2 on 2021-04-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_empleadosregistrados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpleadosRegistrados',
        ),
    ]
