version: '3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
  gourmet:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_data: