# Generated by Django 2.2 on 2021-04-28 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.datetime.today)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('detalle', models.TextField(max_length=300)),
                ('celiaco', models.BooleanField(default=False, verbose_name='Apto celíaco')),
                ('vegano', models.BooleanField(default=False, verbose_name='Vegano')),
                ('delivery', models.BooleanField(default=False, verbose_name='Delivery')),
                ('ruta_imagen', models.FileField(blank=True, null=True, upload_to='menu/img/%Y/%m/%d')),
                ('precio', models.FloatField()),
                ('estado', models.CharField(choices=[('Sin stock', 'Sin stock'), ('Publicado', 'Publicado'), ('Pausado', 'Pausado')], default='Pausado', max_length=200)),
                ('categoria', models.ManyToManyField(to='menu.Categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
