# Generated by Django 2.2 on 2021-04-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ruta_imagen',
            field=models.FileField(blank=True, null=True, upload_to='menu/img/%Y/%m/%d'),
        ),
    ]
